services:
  - type: web
    name: assignpad
    env: python
    buildCommand: ""
    startCommand: daphne assignPad.asgi:application
    envVars:
      - key: DATABASE_URL
        value: postgresql://assignpad_db_user:G77Y3Z9V1MoISE3JEoXr8d5vZta9e0Ee@dpg-d0j5762li9vc73batip0-a.oregon-postgres.render.com/assignpad_db
